"""Typed Python client for the HMIS Inference API.

Auto-generated by ``scripts/generate_sdk.py`` from the OpenAPI schema.
Refresh after endpoint changes — the file is fully regenerated on each
invocation so do not hand-edit it.
"""

from __future__ import annotations

import json
from typing import Any, Optional


class HmisClient:
    """Synchronous HTTP client for the inference endpoints.

    Usage:
        from hmis_inference_client import HmisClient
        with HmisClient(base_url="http://localhost:8000", token="...") as c:
            c.login("alice@example.invalid", "hunter2")
            memo = c.policy_memo()
            print(memo["data"]["headline"])

    The client does not raise — methods return a ``Result`` that
    exposes ``status_code``, ``ok`` and ``data`` (the parsed body).
    """

    def __init__(self, base_url: str, token: Optional[str] = None, api_key: Optional[str] = None):
        self.base_url = base_url.rstrip("/")
        self._token = token
        self._api_key = api_key
        self._session = None  # lazy-import on first use

    def create_district_api_v1_ingest_district_post(self, body: Optional[dict] = None) -> dict:
        """Create a new district"""
        from urllib.parse import urlencode
        path = '/api/v1/ingest/district'
        body = body
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("POST", path, body=body)

    def create_disease_report_api_v1_ingest_disease_report_post(self, body: Optional[dict] = None) -> dict:
        """Create a new disease report"""
        from urllib.parse import urlencode
        path = '/api/v1/ingest/disease_report'
        body = body
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("POST", path, body=body)

    def create_facility_metrics_api_v1_ingest_facility_metrics_post(self, body: Optional[dict] = None) -> dict:
        """Create new facility metrics"""
        from urllib.parse import urlencode
        path = '/api/v1/ingest/facility_metrics'
        body = body
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("POST", path, body=body)

    def ingest_csv_api_v1_ingest_csv_post(self) -> dict:
        """Bulk-ingest facility_metrics from a CSV body"""
        from urllib.parse import urlencode
        path = '/api/v1/ingest/csv'
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("POST", path, body=body)

    def list_districts_api_v1_districts__get(self) -> dict:
        """List all districts"""
        from urllib.parse import urlencode
        path = '/api/v1/districts/'
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def district_risk_summary_api_v1_districts_risk_summary_get(self) -> dict:
        """Risk summary per district"""
        from urllib.parse import urlencode
        path = '/api/v1/districts/risk-summary'
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def list_facilities_api_v1_facilities__get(self, district_id: Optional[object] = None) -> dict:
        """List all facilities with latest metrics"""
        from urllib.parse import urlencode
        path = '/api/v1/facilities/'
        body = None
        query = {'district_id'}
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def facilities_summary_api_v1_facilities_summary_get(self) -> dict:
        """Get facilities summary stats"""
        from urllib.parse import urlencode
        path = '/api/v1/facilities/summary'
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def get_metric_trend_api_v1_metrics_trend_get(self, facility_id: Optional[object] = None, metric: Optional[object] = None, days: Optional[object] = None) -> dict:
        """Get metric trend for a facility"""
        from urllib.parse import urlencode
        path = '/api/v1/metrics/trend'
        body = None
        query = {'facility_id', 'metric', 'days'}
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def get_forecast_api_v1_forecast__disease__get(self, disease, district_id: Optional[object] = None, horizon_days: Optional[object] = None) -> dict:
        """Get 7-day disease forecast"""
        from urllib.parse import urlencode
        path = '/api/v1/forecast/' + str(disease) + ''
        body = None
        query = {'district_id', 'horizon_days'}
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def get_outbreak_risk_api_v1_inference_outbreak_risk_get(self, district_id: Optional[object] = None, disease_name: Optional[object] = None, force_refresh: Optional[object] = None) -> dict:
        """Workstream 1 — Outbreak Risk per (ward × disease)"""
        from urllib.parse import urlencode
        path = '/api/v1/inference/outbreak-risk'
        body = None
        query = {'district_id', 'disease_name', 'force_refresh'}
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def get_hospital_pressure_api_v1_inference_hospital_pressure_get(self, district_id: Optional[object] = None, facility_id: Optional[object] = None, limit: Optional[object] = None, offset: Optional[object] = None, force_refresh: Optional[object] = None) -> dict:
        """Workstream 2 — Hospital Pressure with 48-hour projection"""
        from urllib.parse import urlencode
        path = '/api/v1/inference/hospital-pressure'
        body = None
        query = {'district_id', 'facility_id', 'limit', 'offset', 'force_refresh'}
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def get_priority_rank_api_v1_inference_priority_rank_get(self, district_id: Optional[object] = None, force_refresh: Optional[object] = None) -> dict:
        """Workstream 3 — Top-5 ranked policy actions for today"""
        from urllib.parse import urlencode
        path = '/api/v1/inference/priority-rank'
        body = None
        query = {'district_id', 'force_refresh'}
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def get_policy_memo_api_v1_inference_policy_memo_get(self, district_id: Optional[object] = None, force_refresh: Optional[object] = None) -> dict:
        """Workstream 4 — LLM-narrated policy memo (aggregated)"""
        from urllib.parse import urlencode
        path = '/api/v1/inference/policy-memo'
        body = None
        query = {'district_id', 'force_refresh'}
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def inference_health_api_v1_inference_health_get(self) -> dict:
        """Inference subsystem health"""
        from urllib.parse import urlencode
        path = '/api/v1/inference/health'
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def list_audit_api_v1_inference_audit__get(self, workstream: Optional[object] = None, severity: Optional[object] = None, district_id: Optional[object] = None, facility_id: Optional[object] = None, window: Optional[object] = None, limit: Optional[object] = None, offset: Optional[object] = None) -> dict:
        """List recent inference_audit rows"""
        from urllib.parse import urlencode
        path = '/api/v1/inference/audit/'
        body = None
        query = {'workstream', 'severity', 'district_id', 'facility_id', 'window', 'limit', 'offset'}
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def get_digest_api_v1_inference_audit_digest_get(self, fmt: Optional[object] = None, window: Optional[object] = None) -> dict:
        """Weekly digest — markdown or json"""
        from urllib.parse import urlencode
        path = '/api/v1/inference/audit/digest'
        body = None
        query = {'fmt', 'window'}
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def get_audit_api_v1_inference_audit__trace_id__get(self, trace_id) -> dict:
        """Detail of one audit row by trace_id"""
        from urllib.parse import urlencode
        path = '/api/v1/inference/audit/' + str(trace_id) + ''
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def facility_drilldown_api_v1_inference_drilldown_facility__facility_id__get(self, facility_id) -> dict:
        """Drilldown detail for one facility"""
        from urllib.parse import urlencode
        path = '/api/v1/inference/drilldown/facility/' + str(facility_id) + ''
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def district_disease_drilldown_api_v1_inference_drilldown_district_get(self, district_id: Optional[object] = None, disease: Optional[object] = None) -> dict:
        """Drilldown detail for one (district × disease)"""
        from urllib.parse import urlencode
        path = '/api/v1/inference/drilldown/district'
        body = None
        query = {'district_id', 'disease'}
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def stream_events_api_v1_realtime_events_get(self) -> dict:
        """SSE stream of inference events"""
        from urllib.parse import urlencode
        path = '/api/v1/realtime/events'
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def stream_priority_api_v1_realtime_priority_get(self) -> dict:
        """SSE stream of CRITICAL transitions only"""
        from urllib.parse import urlencode
        path = '/api/v1/realtime/priority'
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def get_metrics_metrics_get(self) -> dict:
        """Prometheus-style metrics for inference"""
        from urllib.parse import urlencode
        path = '/metrics'
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def snapshot_metrics_internal_get(self) -> dict:
        """Internal snapshot (Phase 5)"""
        from urllib.parse import urlencode
        path = '/metrics/internal'
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def login_api_v1_auth_login_post(self, body: Optional[dict] = None) -> dict:
        """Login"""
        from urllib.parse import urlencode
        path = '/api/v1/auth/login'
        body = body
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("POST", path, body=body)

    def refresh_api_v1_auth_refresh_post(self, body: Optional[dict] = None) -> dict:
        """Refresh"""
        from urllib.parse import urlencode
        path = '/api/v1/auth/refresh'
        body = body
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("POST", path, body=body)

    def me_api_v1_auth_me_get(self) -> dict:
        """Me"""
        from urllib.parse import urlencode
        path = '/api/v1/auth/me'
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def register_api_v1_auth_register_post(self, body: Optional[dict] = None) -> dict:
        """Register"""
        from urllib.parse import urlencode
        path = '/api/v1/auth/register'
        body = body
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("POST", path, body=body)

    def logout_api_v1_auth_logout_post(self) -> dict:
        """Logout"""
        from urllib.parse import urlencode
        path = '/api/v1/auth/logout'
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("POST", path, body=body)

    def root__get(self) -> dict:
        """Root"""
        from urllib.parse import urlencode
        path = '/'
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def health_deep_health_deep_get(self) -> dict:
        """Deep health probe — DB/Redis/Celery"""
        from urllib.parse import urlencode
        path = '/health/deep'
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)

    def health_legacy_health_get(self) -> dict:
        """Liveness (legacy) — returns overall OK string"""
        from urllib.parse import urlencode
        path = '/health'
        body = None
        query = None
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("GET", path, body=body)
    # ----- internal -----

    def _request(self, method: str, path: str, body=None):
        """Issue one HTTP request via urllib (avoid an extra dep)."""
        import json as _json
        import urllib.request as _req

        url = self.base_url + path
        data = _json.dumps(body).encode("utf-8") if body is not None else None
        req = _req.Request(url, data=data, method=method)
        req.add_header("Content-Type", "application/json")
        if self._token:
            req.add_header("Authorization", "Bearer " + self._token)
        if self._api_key:
            req.add_header("X-API-Key", self._api_key)
        try:
            with _req.urlopen(req, timeout=120) as resp:
                payload = resp.read().decode("utf-8")
                return {
                    "status_code": resp.status,
                    "ok":          200 <= resp.status < 300,
                    "data":        _json.loads(payload) if payload else None,
                }
        except Exception as exc:  # noqa: BLE001
            return {"status_code": 0, "ok": False, "error": str(exc)}

    def __enter__(self):
        return self

    def __exit__(self, *args):
        return False
