#!/usr/bin/env python3
"""Bootstrap a service-account user (non-Commissioner). Idempotent.

Usage:
    python scripts/create_user_for_service.py \
        --email ingest-bot@example.invalid \
        --name "CSV Ingest Bot" \
        --role STATE_OFFICER \
        [--password <auto-generated -> printed to stdout>]

Sets ``is_active = TRUE`` on conflict, so re-running is safe.
"""
import argparse
import os
import secrets
import string
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_DIR))


def _pg_conn():
    import psycopg2
    import urllib.parse
    parsed = urllib.parse.urlparse(
        os.environ.get(
            "DATABASE_URL", "postgresql://hmis:hmis_password@localhost:5432/hmis"
        ),
    )
    return psycopg2.connect(
        host=parsed.hostname or "localhost",
        port=parsed.port or 5432,
        database=parsed.path.lstrip("/") or "hmis",
        user=parsed.username or "hmis",
        password=parsed.password or "hmis_password",
    )


def _random_password(length: int = 28) -> str:
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*-_=+?"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--email", required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument(
        "--role",
        default="STATE_OFFICER",
        choices=["COMMISSIONER", "STATE_OFFICER", "DISTRICT_OFFICER", "FACILITY_HEAD", "VIEWER"],
    )
    ap.add_argument(
        "--password",
        default=None,
        help="Generate one if not supplied. Output to stdout on success.",
    )
    args = ap.parse_args()

    from backend.security import hash_password
    password = args.password or _random_password()
    hashed = hash_password(password)

    conn = _pg_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO users (email, full_name, hashed_password, role)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (email) DO UPDATE
                SET full_name = EXCLUDED.full_name,
                    hashed_password = EXCLUDED.hashed_password,
                    role = EXCLUDED.role,
                    is_active = TRUE
                """,
                (args.email.strip().lower(), args.name, hashed, args.role),
            )
        conn.commit()
        print(f"User ready: {args.email}")
        if not args.password:
            print(f"  Password: {password}")
            print("  ^ Save this — it won't be shown again.")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
