#!/usr/bin/env python3
"""Generate a typed Python SDK from FastAPI's OpenAPI schema.

Reads ``backend.main.app.openapi()`` and emits a single class
``HmisClient`` that wraps every endpoint as a method on this single
class. The generated module is a *starter* — operators can either
consume it directly or use it as a starting point for a richer SDK
with proper type annotations.

Output: ``hmis_inference_client/__init__.py`` (sibling to ``backend/``).

Usage:
    python scripts/generate_sdk.py
"""
from __future__ import annotations

import importlib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))


_HEADER = '''"""Typed Python client for the HMIS Inference API.

Auto-generated by ``scripts/generate_sdk.py`` from the OpenAPI schema.
Refresh after endpoint changes — the file is fully regenerated on each
invocation so do not hand-edit it.
"""

from __future__ import annotations

import json
from typing import Any, Optional


class HmisClient:
    """Synchronous HTTP client for the inference endpoints.

    Usage:
        from hmis_inference_client import HmisClient
        with HmisClient(base_url="http://localhost:8000", token="...") as c:
            c.login("alice@example.invalid", "hunter2")
            memo = c.policy_memo()
            print(memo["data"]["headline"])

    The client does not raise — methods return a ``Result`` that
    exposes ``status_code``, ``ok`` and ``data`` (the parsed body).
    """

    def __init__(self, base_url: str, token: Optional[str] = None, api_key: Optional[str] = None):
        self.base_url = base_url.rstrip("/")
        self._token = token
        self._api_key = api_key
        self._session = None  # lazy-import on first use

'''


_METHOD_TEMPLATE = '''    def {name}(self{args}) -> dict:
        """{summary}

        Generated from the OpenAPI spec. Arguments are flattened
        from path params + query + body.
        """
        path = "{path}"
        body = {body_expr}
        query = {query_expr}
        if query:
            path += "?" + urlencode({k: v for k, v in query.items() if v is not None})
        return self._request("{method}", path, body=body)
'''
# _METHOD_TEMPLATE is retained in case we want to drop a named-template
# version back in; rendering in the current pass assembles blocks by
# string concatenation to avoid colliding with the URL-template braces.
del _METHOD_TEMPLATE


_FOOTER = '''    # ----- internal -----

    def _request(self, method: str, path: str, body=None):
        """Issue one HTTP request via urllib (avoid an extra dep)."""
        import json as _json
        import urllib.request as _req

        url = self.base_url + path
        data = _json.dumps(body).encode("utf-8") if body is not None else None
        req = _req.Request(url, data=data, method=method)
        req.add_header("Content-Type", "application/json")
        if self._token:
            req.add_header("Authorization", "Bearer " + self._token)
        if self._api_key:
            req.add_header("X-API-Key", self._api_key)
        try:
            with _req.urlopen(req, timeout=120) as resp:
                payload = resp.read().decode("utf-8")
                return {
                    "status_code": resp.status,
                    "ok":          200 <= resp.status < 300,
                    "data":        _json.loads(payload) if payload else None,
                }
        except Exception as exc:  # noqa: BLE001
            return {"status_code": 0, "ok": False, "error": str(exc)}

    def __enter__(self):
        return self

    def __exit__(self, *args):
        return False
'''


def _method_name(operation_id: str) -> str:
    # operation_id is usually "get_outbreak_risk" — keep that.
    return operation_id or "anonymous"


def _summarise(operation: dict) -> str:
    return (
        operation.get("summary")
        or operation.get("description")
        or "(no summary provided)"
    )


def _snake_to_kebab(s: str) -> str:
    return s.replace("_", "-")


# Endpoints we don't want to expose as methods on the SDK (options,
# auth refresh on top of login works fine via token replacement).
_SKIP_OPERATION_IDS = {"get_root", "get_health"}


def _ensure_backend_loaded():
    """Reuse the Quick Start lifespan without actually running it."""
    from backend.main import app
    return app


def render_methods(paths: dict) -> list[str]:
    blocks: list[str] = []
    for path, items in paths.items():
        for method, op in items.items():
            if method.lower() not in ("get", "post", "put", "delete", "patch"):
                continue
            op_id = op.get("operationId")
            if not op_id or op_id in _SKIP_OPERATION_IDS:
                continue

            params_in_path: list[tuple[str, str]] = []
            params_in_query: list[tuple[str, str]] = []
            body_schema: dict | None = None
            request_body = op.get("requestBody")
            if request_body:
                content = request_body.get("content", {})
                app_json = content.get("application/json") or content.get("*/*")
                if app_json:
                    body_schema = app_json.get("schema", {})

            for p in op.get("parameters", []) or []:
                name = p.get("name", "")
                kind = p.get("in", "query")
                ptype = p.get("schema", {}).get("type", "string")
                if kind == "path":
                    params_in_path.append((name, ptype))
                elif kind == "query":
                    params_in_query.append((name, ptype))

            args = []
            for name, _ in params_in_path:
                args.append(f"{_safe(name)}")
            for name, _ in params_in_query:
                args.append(f"{_safe(name)}: Optional[object] = None")
            if body_schema is not None and method.lower() in ("post", "put", "patch"):
                args.append("body: Optional[dict] = None")

            args_str = (", " + ", ".join(args)) if args else ""

            if params_in_path:
                # Build the path expression by interleaving string
                # literals and `str(...)` substitutions — the curly
                # braces in path templates are *not* part of a
                # Python format string here.
                parts = re.split(r"(\{[^}]+\})", path)
                rendered: list[str] = []
                for part in parts:
                    if part.startswith("{") and part.endswith("}"):
                        rendered.append(f"str({_safe(part[1:-1])})")
                    else:
                        rendered.append(repr(part))
                path_expr = " + ".join(rendered)
            else:
                path_expr = repr(path)

            query_expr_parts = []
            for name, _ in params_in_query:
                query_expr_parts.append(repr(name))
            query_expr = "{" + ", ".join(query_expr_parts) + "}" if query_expr_parts else "None"

            body_expr = "body" if body_schema else "None"
            summary = _summarise(op).replace('"', '\\"')

            # Build the method body manually to avoid conflicts with
            # the {} placeholders coming from path templates.
            arg_list = args_str
            block = (
                f'    def {op_id}(self{arg_list}) -> dict:\n'
                f'        """{summary}"""\n'
                f'        from urllib.parse import urlencode\n'
                f'        path = {path_expr}\n'
                f'        body = {body_expr}\n'
                f'        query = {query_expr}\n'
                f'        if query:\n'
                f'            path += "?" + urlencode({{k: v for k, v in query.items() if v is not None}})\n'
                f'        return self._request("{method.upper()}", path, body=body)\n'
            )
            blocks.append(block)

    return blocks


def _safe(name: str) -> str:
    # Common keywords / dunder names surface in path params.
    if name in {"type", "class", "from", "import", "return", "id", "in"}:
        return name + "_"
    return name


def _ensure_module_writable(path: Path) -> None:
    """Recreate the SDK module path; we keep this idempotent."""
    import shutil
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def main() -> None:
    app = _ensure_backend_loaded()
    spec = app.openapi()

    out_dir = REPO / "hmis_inference_client"
    _ensure_module_writable(out_dir)

    methods = render_methods(spec.get("paths", {}))

    pkg_init = out_dir / "__init__.py"
    with pkg_init.open("w", encoding="utf-8") as f:
        f.write(_HEADER)
        f.write("\n".join(methods))
        f.write(_FOOTER)

    print(f"Wrote {pkg_init} ({len(methods)} SDK methods)")


if __name__ == "__main__":
    main()
